String escapes
Hubro/tree-sitter-yang pull request #3
Opened 2021-07-24 15:48 UTC by dimbleby

Some comments

- This all looks right to me, but I'm a treesitter noob so don't trust me on that
- I couldn't figure out how to exclude comment sequences from unquoted strings, so I haven't
- I wasn't sure whether it was expected to include negative tests in the corpus ie to include the things that should fail to parse and verify that we get an error.  This doesn't seem to be the done thing in a couple of parsers that I looked at, so I didn't do it here either
- neovim by default doesn't link errors to any highlight group (because it's too annoying while you're typing apparently) so the query for errors doesn't do anything unless your colorscheme explicitly adds something for `TSError`.

2021-07-25 22:10 UTC, Hubro commented
Thanks for the contribution! :grin: 

There seems to be some errors produced when parsing the standard models though:

```
$ ./scripts/test-parsing-yang-modules.sh
```

```
Total parses: 368; successful parses: 363; failed parses: 5; success percentage: 98.64%
```

Could you check that out?

2021-07-25 22:11 UTC, Hubro requested changes
Thanks for the contribution! :grin: 

There seems to be some errors produced when parsing the standard models though:

```
$ ./scripts/test-parsing-yang-modules.sh
```

```
Total parses: 368; successful parses: 363; failed parses: 5; success percentage: 98.64%
```

Could you check that out?

2021-07-25 23:08 UTC, dimbleby commented
Oh, interesting.

Looks like the problematic files have `pattern`s, like:

```
  typedef ieNameType {
    type string {
      length "1..max";
      pattern "\S+";
    }
    description "Type for Information Element names.  Whitespaces
      are not allowed.";
  }
```

But according to 6.1.3:

> The backslash MUST NOT be followed by any other character.

which would make that double-quoted pattern completely not OK.

[9.4.5](https://datatracker.ietf.org/doc/html/rfc7950#section-9.4.5) says:

> The "pattern" statement, which is an optional substatement to the
> "type" statement, takes as an argument a regular expression string,
> as defined in [XSD-TYPES].

Not too sure how these parts of the spec can be reconciled, except perhaps by interpreting a "regular expression string" to be somehow outside of the normal rules for strings. 

Awkward!

2021-07-25 23:11 UTC, dimbleby commented
https://github.com/YangModels/yang/issues/366 suggests that the parser is right and the models are wrong.

2021-07-25 23:14 UTC, dimbleby commented
So I think probably the way to resolve this is to exclude those faulty models from that test.  What do you think?

2021-07-26 00:21 UTC, Hubro commented
One thing I'm not entirely clear on, is the string argument for `pattern` interpreted just like a normal string, or is it a special case? Does the YANG compiler complain about `"\S+"` or does it work? :thinking:

2021-07-26 08:10 UTC, dimbleby commented
I can't see any justification for treating `pattern` strings as a special case: so far as I can see those models are simply bad.

Presumably we have slightly different versions of tree-sitter CLI.  I am usuing v0.20.0, which I have compiled locally.

The other idea I had re fixing up the testing of parsing standard YANG modules was that we could patch them to be correct before testing.  Slightly more trouble than excluding the bad models completely, but maybe better?

2021-07-26 16:01 UTC, Hubro approved these changes

2021-07-26 16:02 UTC, merged

2021-07-26 16:02 UTC, Hubro commented
Thanks for the contribution!